### ISSUE TITLE
The game crashes when destroying mod objects

### ISSUE THREAD

**Issue by tammagotchiii** [pau101/Fairy-Lights#65] opened 2019-12-13 22:30 UTC
Described the problem earlier, as well as in the topic title.

Sorry for the possible mistakes and incorrect design of the topic, I don’t understand anything here, since I don’t speak English.

Game version: ForgeOptiFine 1.14.4
Forge: 28.1.90

Crash Log:
[link on pastebin](https://pastebin.com/h79G2FDa)

**Comment by pau101** [comment] 2019-12-14 00:06
Thanks for reporting! This appears to be a duplicate of #64 which has been fixed in [2.1.12](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2842209)

**Closed by pau101** 2019-12-14 00:06 UTC
