### ISSUE TITLE
white lights showing up as blue

### ISSUE THREAD

**Issue by yeet55yeet** [pau101/Fairy-Lights#51] opened 2018-10-06 18:36 UTC
i first noticed it after i updated to 2.1.2 and white lights are still showing up blue for me as of 2.1.4.

**Comment by pau101** [comment] 2018-10-06 18:41
Thanks for the report, however this is a duplicate of #37. I'll get to this issue soon enough.

**Closed by pau101** 2018-10-06 18:41 UTC
