### ISSUE TITLE
Letter bunting cannot be placed in 1.16.4

### ISSUE THREAD

**Issue by lolabirde** [pau101/Fairy-Lights#110] opened 2021-01-22 00:13 UTC
it has a quick flash but but does not place. Ends up back in hand.

**Comment by StokedTheorem** [comment] 2021-01-22 23:14
I am having this same issue

**Comment by voodoofrog** [comment] 2021-02-04 16:08
As am I.

**Comment by pau101** [comment] 2021-02-07 22:57
Closing as should be a duplicate of #110

**Closed by pau101** 2021-02-07 22:57 UTC

**Comment by jexom** [comment] 2021-06-14 12:08
Having ther same problem in 1.16.5. You just closed the issue because it's a duplicate of itself
