### ISSUE TITLE
Recipes Fail to Register in Forge Multiplayer [1.15.2]

### ISSUE THREAD

**Issue by Mw119** [pau101/Fairy-Lights#95] opened 2020-11-16 21:27 UTC
I've tested a variety of versions of Fairy Lights between 3.0.0, and the latest 3.0.14.
All recipes will properly register in Singleplayer, making them craftable. Whenever you load into multiplayer however, most of these recipes are not registered, making many things uncraftable.

I have tested both within a mod list as well as standalone with forge + JEI, and in both situations multiplayer fails to allow these recipes to be craftable.

Please let me know if I am doing something wrong.

**Comment by pau101** [comment] 2020-11-17 00:33
Thanks for reporting!

I am unable to reproduce this issue with latest Forge and Fairy Lights, what mods do you have installed?

**Comment by Mw119** [comment] 2020-11-17 04:21
I just tested on a freshly installed client/server and it still fails to register the recipes

Forge- 31.2.45
Fairy Lights 3.0.14
JEI - 6.0.3.15

I'm not sure what I am doing wrong. Surely it couldn't be JEI?

**Comment by pau101** [comment] 2020-11-17 05:57
Testing with those versions works for me. Could you provide me a screenshot of crafting an item and it not working?

**Comment by Mw119** [comment] 2020-11-17 07:50
So in my isolated testing I got the crafting to work, but only by using the recipe book and knowing the recipes. JEI did **NOT** return any results for most of the crafting.
[mods](https://gyazo.com/6d1e9d417c596faa2c3883d8edb3b32c)

I sifted through JEI and found empty [results](https://gyazo.com/365c2cca58cac231054c7557b2d5c045)for some of the items
[results pt2](https://gyazo.com/91040bfa2a24387b2f5d78e751c327cc)
[I think this one is garland](https://gyazo.com/120a68bccb6fa27fe742d9fb710521a5)

The server with the full list of mods would regularly assign lights crafting to other crafting stations like Create's Mixer. I was assuming fixing in isolation would in tandem fix the full modded server.
Should I try testing there instead or continue in isolation? Could it be JEI somehow?

**Comment by pau101** [comment] 2020-11-17 08:31
If you are to craft the recipes they are are working correctly, however JEI is simply unable to display them. Do you have any custom data packs in use?

**Comment by Mw119** [comment] 2020-11-17 09:39
No custom data packs are used. [Here](https://gyazo.com/4179cc41a1eea43d270875b86315d49b) is an example of JEI botching crafting registry. No Crafting Table recipe shows up, resulting in players being confused over how to properly craft the few lights that improperly display.

**Comment by pau101** [comment] 2020-11-17 10:38
Could you send me the server "logs/debug.txt"?

**Comment by Mw119** [comment] 2020-11-17 19:41
[2020-11-15-1.log.gz](https://github.com/pau101/Fairy-Lights/files/5555833/2020-11-15-1.log.gz)
[debug.log](https://github.com/pau101/Fairy-Lights/files/5555836/debug.log)

**Comment by pau101** [comment] 2020-11-17 20:38
Thank you, and to clarify when you did a fresh install you only had Forge, Fairy Lights, and JEI on a fresh world correct? Could you provide that log as well?

**Comment by Mw119** [comment] 2020-11-17 23:35
[2020-11-17-1.log.gz](https://github.com/pau101/Fairy-Lights/files/5556804/2020-11-17-1.log.gz)
[debug.log](https://github.com/pau101/Fairy-Lights/files/5556805/debug.log)

Here are the logs for the isolated test as well. Let me know if I did something wrong

**Comment by pau101** [comment] 2020-11-18 00:51
Was a fresh a world created for the isolated test?

**Comment by Mw119** [comment] 2020-11-18 02:43
Yes it was, however i continued testing with it past the first time when I encountered issues.

**Comment by pau101** [comment] 2020-11-18 03:24
I tested again, but removed some extra mods I had left on the server, which was JER, and I am getting what you are now. Could you see if putting that mod on the server helps? You can get it [here](https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer/files/2946240). I will look further into the issue in the meantime.

**Comment by pau101** [comment] 2020-11-18 04:15
When the issue happens is it purely Fairy Lights recipes having issues?

**Comment by Mw119** [comment] 2020-11-18 05:45
The only recipes Ive seen missing or obstructed are Fairy Light's, but I will do a cursory look over everything as well.

**Comment by Mw119** [comment] 2020-11-18 05:55
After reviewing most recipes, it seems that indeed only Fairy Lights recipes are being tampered with.

**Comment by Mw119** [comment] 2020-11-18 06:49
Could it have anything to do with forge dictionaries? The only recipes that appear don't use any dictionary items are don't cycle.

**Comment by pau101** [comment] 2020-11-18 19:29
Yes the ingredients I saw being blank were ones which used tags. Are you able to place fairy lights fine on the server?

**Comment by pau101** [comment] 2020-11-18 19:40
Oh and could you send me the isolated client logs as well?

**Comment by pau101** [comment] 2020-11-18 20:22
Okay after looked further, doing a `/reload` should definitely fix it and this is a bug which JEI has to resolve.

**Comment by Mw119** [comment] 2020-11-18 20:43
/reload does indeed fix the issue. Does that have to be done per server reboot or per client? Should I follow up with JEI issues?
Do you also still want the isolated logs with reload?

**Comment by pau101** [comment] 2020-11-18 21:51
Per client joining yes so it is not a solid fix but it did confirm the issue, and no more logs are necessary. I privately spoke to @mezz and submitting an issue there would be good.

**Comment by jarocajavi** [comment] 2020-12-25 01:55
Hi, the issue still, i have a single player modpack open in LAN, and the recipes show to me (the owner) but the other players can craft the item but no see the recipes. @mezz know this? Will be fix in the next update?

Thanks!! And mery christmas!

**Comment by pau101** [comment] 2021-02-25 01:53
Closing as this issue was resolved in JEI 1.16.4-7.6.1.68

**Closed by pau101** 2021-02-25 01:53 UTC
