### ISSUE TITLE
Unable to place hanging lights anywhere 

### ISSUE THREAD

**Issue by Ezg899** [pau101/Fairy-Lights#108] opened 2021-01-07 02:47 UTC
Everytime i go to place the hanging lights they don't appear 
Version 1.16.4
forge version 1.16.4
https://user-images.githubusercontent.com/45400373/103844799-551d5400-5060-11eb-8ffe-7d19b0d7aade.mov

**Comment by pau101** [comment] 2021-01-09 06:09
Thanks for reporting! Can you reproduce this issue with only Fairy Lights installed?

**Comment by StokedTheorem** [comment] 2021-01-18 06:03
I'm having a similar issue but with the hanging letters. The letters won't be placed, but the lights can be.

**Comment by Ezg899** [comment] 2021-01-20 22:58
I am sorry for taking forever to reply i have been gone but i am pretty sure it is not working because of a world mod i downloaded
it worked before that

**Comment by BrangGit** [comment] 2021-01-27 21:19
Same issue here. Here's our modlist : https://docs.google.com/document/d/1adjNQ5r0FcN6plQG0SylZXe1fT3s-Ua-qdhCptyPOBU/edit

**Comment by pau101** [comment] 2021-01-28 02:20
Thank for the mod list. Did you craft or use the creative menu to obtain the lights you're trying to place?

**Comment by Ezg899** [comment] 2021-01-28 02:27
https://docs.google.com/document/d/1WstZY1Q1DiFQCyIrrbu6J_jxnyLAWwpiPx2_Lf2VgRU/edit?usp=sharing here are the mods i have

**Comment by BrangGit** [comment] 2021-01-28 13:38
The lights have been crafted in survival mode. 
Thanks for sharing Ezg899. Here's the mods we have in common :
- BiomesOplenty
- Curios-forge 
- Dungeons_gear
- Just Enough Items
- Towers_of_the_wild

I'll do some tests with and without those mods and will keep in touch.

**Comment by BrangGit** [comment] 2021-01-31 17:49
Hi, I can't reproduce the issue, after restarting the server, everything seems to work just fine.

**Comment by Ezg899** [comment] 2021-02-01 22:19
Oh thanks i never thought about doing that but it is odd on why we cant place them without having to craft the hanging lights

**Comment by pau101** [comment] 2021-02-02 03:27
@BrangGit This type of issue comes from mods trying to add their own data onto the fairy lights items, which breaks placement able to match up what is being held to the strand that is trying to be placed. It looks like either Dungeons gear or Towers of the wild is responsible. I can look into resolving this incompatibility.

@Ezg899 I was asking because if you used `give` those lights are invalid as they have no data for what their pattern should be, the creative menu should work.

**Comment by pau101** [comment] 2021-02-25 03:04
Fixed in [Release 4.0.5](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3216206)

**Closed by pau101** 2021-02-25 03:04 UTC

**Comment by Sazuzaki** [comment] 2023-05-11 05:01
This bug is present again in 1.19.2. I tried crafting with the correct recipe yet it doesn't appear. Also tried getting lights through creative and placing them that way, but that also doesn't work. Same bug as seen in the video of this report.

https://pastebin.com/DubtAAaT

**Comment by TheOtherworldly** [comment] 2023-06-02 20:41
This bug is happening to me in 1.16.5

**Comment by vinnyg0621** [comment] 2023-06-25 01:26
can someone please just fix this bug in 1.19????
