### ISSUE TITLE
[1.16.4-4.0.2] lightnig block client crash

### ISSUE THREAD

**Issue by Daejangnamu** [pau101/Fairy-Lights#98] opened 2020-11-24 09:55 UTC
---- Minecraft Crash Report ---- // My bad. Time: 20. 11. 24 오후 6:19 Description: Unexpected error java.lang.NullPointerException: Unexpected error 	at net.minecraft.world.lighting.SectionLightStorage.func_215521_h(SourceFile:96) ~[?:?] {re:classloading} 	at net.minecraft.world.lighting.LightEngine.func_215471_c(LightEngine.java:129) ~[?:?] {re:classloading} 	at net.minecraft.world.lighting.LevelBasedGraph.func_215469_a(LevelBasedGraph.java:122) ~[?:?] {re:classloading} 	at net.minecraft.world.lighting.BlockLightEngine.func_215623_a(BlockLightEngine.java:118) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.HangingLightsConnection.setLight(HangingLightsConnection.java:261) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.HangingLightsConnection.onUpdate(HangingLightsConnection.java:143) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.Connection.lambda$update$2(Connection.java:278) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.Connection$$Lambda$7620/951849613.apply(Unknown Source) ~[?:?] {} 	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:206) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.Connection.update(Connection.java:275) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.fastener.AbstractFastener.update(AbstractFastener.java:98) ~[?:?] {re:classloading} 	at me.paulf.fairylights.client.ClientEventHandler$$Lambda$7618/345104268.accept(Unknown Source) ~[?:?] {} 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {} 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {} 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {} 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {} 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {} 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {} 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {} 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {} 	at me.paulf.fairylights.client.ClientEventHandler.onClientTick(ClientEventHandler.java:82) ~[?:?] {re:classloading} 	at net.minecraftforge.eventbus.ASMEventHandler_226_ClientEventHandler_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {} 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {} 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110) ~[?:?] {re:classloading} 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1542) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.0.jar:35.1] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/884502914.call(Unknown Source) [forge-1.16.4-35.1.0.jar:35.1] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading} A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Render thread Stacktrace: 	at net.minecraft.world.lighting.SectionLightStorage.func_215521_h(SourceFile:96) ~[?:?] {re:classloading} 	at net.minecraft.world.lighting.LightEngine.func_215471_c(LightEngine.java:129) ~[?:?] {re:classloading} 	at net.minecraft.world.lighting.LevelBasedGraph.func_215469_a(LevelBasedGraph.java:122) ~[?:?] {re:classloading} 	at net.minecraft.world.lighting.BlockLightEngine.func_215623_a(BlockLightEngine.java:118) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.HangingLightsConnection.setLight(HangingLightsConnection.java:261) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.HangingLightsConnection.onUpdate(HangingLightsConnection.java:143) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.Connection.lambda$update$2(Connection.java:278) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.Connection$$Lambda$7620/951849613.apply(Unknown Source) ~[?:?] {} 	at net.minecraftforge.common.util.LazyOptional.map(LazyOptional.java:206) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.connection.Connection.update(Connection.java:275) ~[?:?] {re:classloading} 	at me.paulf.fairylights.server.fastener.AbstractFastener.update(AbstractFastener.java:98) ~[?:?] {re:classloading} 	at me.paulf.fairylights.client.ClientEventHandler$$Lambda$7618/345104268.accept(Unknown Source) ~[?:?] {} 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {} 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {} 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {} 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {} 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {} 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {} 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {} 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {} 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {} 	at me.paulf.fairylights.client.ClientEventHandler.onClientTick(ClientEventHandler.java:82) ~[?:?] {re:classloading} 	at net.minecraftforge.eventbus.ASMEventHandler_226_ClientEventHandler_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?] {} 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {} 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {} 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110) ~[?:?] {re:classloading} -- Affected level -- Details: 	All players: 3 total; [ClientPlayerEntity['tree_doll'/9192211, l='ClientLevel', x=-236.78, y=54.20, z=832.61], RemoteClientPlayerEntity['ITAR76'/5597038, l='ClientLevel', x=-238.37, y=54.20, z=843.99], RemoteClientPlayerEntity['kikiya_'/9506359, l='ClientLevel', x=-237.54, y=48.00, z=827.88]] 	Chunk stats: Client Chunk Cache: 441, 345 	Level dimension: minecraft:overworld 	Level spawn location: World: (-220,67,247), Chunk: (at 4,4,7 in -14,15; contains blocks -224,0,240 to -209,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511) 	Level time: 48108037 game time, 5129643 day time 	Server brand: forge 	Server type: Non-integrated multiplayer server Stacktrace: 	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default} 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A} 	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A} 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {} 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {} 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {} 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.0.jar:35.1] {} 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/884502914.call(Unknown Source) [forge-1.16.4-35.1.0.jar:35.1] {} 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {} 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {} 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {re:classloading} 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {re:classloading} -- System Details -- Details: 	Minecraft Version: 1.16.4 	Minecraft Version ID: 1.16.4 	Operating System: Windows 10 (amd64) version 10.0 	Java Version: 1.8.0_51, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation 	Memory: 2683146880 bytes (2558 MB) / 5335154688 bytes (5088 MB) up to 8589934592 bytes (8192 MB) 	CPUs: 12 	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M 	ModLauncher: 8.0.6+85+master.325de55 	ModLauncher launch target: fmlclient 	ModLauncher naming: srg 	ModLauncher services: 		/mixin-0.8.2.jar mixin PLUGINSERVICE 		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 		/forge-1.16.4-35.1.0.jar object_holder_definalize PLUGINSERVICE 		/forge-1.16.4-35.1.0.jar runtime_enum_extender PLUGINSERVICE 		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 		/forge-1.16.4-35.1.0.jar capability_inject_definalize PLUGINSERVICE 		/forge-1.16.4-35.1.0.jar runtimedistcleaner PLUGINSERVICE 		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 		/OptiForge-MC1.16.4-0.4.1.jar optiforge TRANSFORMATIONSERVICE 		/forge-1.16.4-35.1.0.jar fml TRANSFORMATIONSERVICE 		/OptiForge-MC1.16.4-0.4.1.jar FakeOptiFine TRANSFORMATIONSERVICE 		/OptiForge-MC1.16.4-0.4.1.jar optiforgewrapper TRANSFORMATIONSERVICE 	FML: 35.1 	Forge: net.minecraftforge:35.1.0 	FML Language Providers: 		javafml@35.1 		minecraft@1 	Mod List: 		NetherPortalFix_1.16.2-7.1.0.jar |NetherPortalFix |netherportalfix |7.1.0 |DONE |NOSIGNATURE 		Wyrmroost-1.16.3-1.2.7.jar |Wyrmroost |wyrmroost |1.16.3-1.2.7 |DONE |NOSIGNATURE 		mining-helmet-1.16.2-1.0.8.jar |Mining Helmet |mining_helmet |1.0.8 |DONE |NOSIGNATURE 		item-filters-2.2.2.18.jar |Item Filters |itemfilters |2.2.2.18 |DONE |NOSIGNATURE 		jei-1.16.4-7.6.0.58.jar |Just Enough Items |jei |7.6.0.58 |DONE |NOSIGNATURE 		OptiForge-MC1.16.4-0.4.1.jar |OptiForge |optiforge |0.4.1 |DONE |NOSIGNATURE 		mcw-windows-1.0.2-mc1.16.2.jar |Macaw's Windows |mcwwindows |1.0.2 |DONE |NOSIGNATURE 		caelus-forge-1.16.3-2.0.0.3.jar |Caelus API |caelus |1.16.3-2.0.0.3 |DONE |NOSIGNATURE 		bambooeverything-1.16.3-forge-1.0.0.jar |Bamboo Everything |bambooeverything |1.16.3-forge-1.0.0 |DONE |NOSIGNATURE 		colytra-forge-1.16.3-5.0.0.1.jar |Colytra |colytra |1.16.3-5.0.0.1 |DONE |NOSIGNATURE 		Clumps-6.0.0.12.jar |Clumps |clumps |6.0.0.12 |DONE |NOSIGNATURE 		citadel-1.5.2.jar |Citadel |citadel |1.5.2 |DONE |NOSIGNATURE 		DimStorage-1.16.3-4.2.1.jar |DimStorage |dimstorage |4.2.1 |DONE |NOSIGNATURE 		ftb-gui-library-1603.1.1.25.jar |FTB GUI Library |ftbguilibrary |1603.1.1.25 |DONE |NOSIGNATURE 		decorative_blocks-1.16.2-1.1.jar |Decorative Blocks |decorative_blocks |1.5 |DONE |NOSIGNATURE 		good-nights-sleep-1.16.3-1.2.8.jar |Good Night's Sleep |good_nights_sleep |1.2.8 |DONE |NOSIGNATURE 		FarmingForBlockheads_1.16.3-7.2.1.jar |Farming for Blockheads |farmingforblockheads |7.2.1 |DONE |NOSIGNATURE 		Bookshelf-1.16.4-9.0.7.jar |Bookshelf |bookshelf |9.0.7 |DONE |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0 		Coins-1.16.4-5.0.1.jar |Coins |coins |5.0.1 |DONE |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0 		additional_lights-1.16.3-2.1.2.jar |Additional Lights |additional_lights |2.1.2 |DONE |NOSIGNATURE 		iceandfire-2.1.3-1.16.4.jar |Ice and Fire |iceandfire |2.1.3-1.16.4 |DONE |NOSIGNATURE 		Hwyla-forge-1.10.11-B78_1.16.2.jar |Waila |waila |1.10.11-B78_1.16.2 |DONE |NOSIGNATURE 		Ma-Essentials-1.16.2-3.3.0.jar |Ma Essentials |maessentials |1.16.2-3.3.0 |DONE |NOSIGNATURE 		CraftTweaker-1.16.4-7.0.0.63.jar |CraftTweaker |crafttweaker |7.0.0.63 |DONE |NOSIGNATURE 		ftb-teams-1.0.1.12.jar |FTB Teams |ftbteams |1.0.1.12 |DONE |NOSIGNATURE 		ftb-chunks-1603.1.2.41.jar |FTB Chunks |ftbchunks |1603.1.2.41 |DONE |NOSIGNATURE 		forge-1.16.4-35.1.0-universal.jar |Forge |forge |35.1.0 |DONE |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90 		shetiphiancore-1.16-3.8.4.jar |ShetiPhian-Core |shetiphiancore |3.8.4 |DONE |NOSIGNATURE 		MmmMmmMmmMmm-1.16-1.0.1.jar |MmmMmmMmmMmm |dummmmmmy |1.0.1 |DONE |NOSIGNATURE 		scuba-gear-1.16.2-1.0.1.jar |Scuba Gear |scuba_gear |1.0.1 |DONE |NOSIGNATURE 		Upgraded+Netherite+1.16.1+-+1.5.1.jar |Upgraded Netherite |upgradednetherite |1.5.0 |DONE |NOSIGNATURE 		forge-1.16.4-35.1.0-client.jar |Minecraft |minecraft |1.16.4 |DONE |NOSIGNATURE 		ftb-quests-1603.1.0.11.jar |FTB Quests |ftbquests |1603.1.0.11 |DONE |NOSIGNATURE 		pamhc2crops-1.16.3-1.0.1.jar |Pam's HarvestCraft 2 Crops |pamhc2crops |version |DONE |NOSIGNATURE 		simplylight-1.16.4-1.1.1.jar |Simply Light |simplylight |1.16.4-1.1.1 |DONE |NOSIGNATURE 		HotLib-1.16.2-0.0.1.jar |HotLib |hotlib |0.0.1 |DONE |NOSIGNATURE 		fairylights-4.0.2-1.16.4.jar |Fairy Lights |fairylights |4.0.2 |DONE |NOSIGNATURE 		JAHM-v1.3.4.1.1-[1.16.2-33.0.3].jar |Just Another Head Mod |justanotherheadmod |1.3.4.1.1 |DONE |NOSIGNATURE 		cookiecore-1.16.2-3.0.0-4d69840.jar |CookieCore |cookiecore |1.16.2-3.0.0-37c5343|DONE |NOSIGNATURE 		magicfeather-1.16.2-3.1.0.jar |Magic Feather |magicfeather |1.16.2-3.1.0 |DONE |NOSIGNATURE 		leap-1.16.2-1.0.1.jar |Leap |leap |1.0.1 |DONE |NOSIGNATURE 		pamhc2foodcore-1.16.3-1.0.0.jar |Pam's HarvestCraft 2 Food Core|pamhc2foodcore |version |DONE |NOSIGNATURE 		camera-1.16.4-1.0.5.jar |Camera Mod |camera |1.16.4-1.0.5 |DONE |NOSIGNATURE 		multibeds-1.16-1.7.5.jar |Multi-Beds |multibeds |1.7.5 |DONE |NOSIGNATURE 		Project+MMO-1.16.2-3.17.6.jar |Project MMO |pmmo |1.16.2-3.17.6 |DONE |NOSIGNATURE 		furniture-7.0.0-pre19-1.16.3.jar |MrCrayfish's Furniture Mod |cfm |7.0.0-pre19 |DONE |NOSIGNATURE 		AI-Improvements-1.16.2-0.3.0.jar |AI-Improvements |aiimprovements |0.3.0 |DONE |NOSIGNATURE 		The_Undergarden-1.16.3-0.3.8.jar |The Undergarden |undergarden |0.3.8 |DONE |NOSIGNATURE 		Aquaculture-1.16.3-2.1.4.jar |Aquaculture 2 |aquaculture |1.16.3-2.1.4 |DONE |NOSIGNATURE 		WatchDog-AntiCheat-1.16.2-0.0.1.jar |WatchDog AntiCheat |watchdog |0.0.1 |DONE |NOSIGNATURE 		ServerTabInfo-1.16.4-1.3.3.jar |Server Tab Info |servertabinfo |1.3.3 |DONE |NOSIGNATURE 	Crash Report UUID: affc13a1-7598-4c9e-989d-96d3666b7064 	Launched Version: 1.16.4-forge-35.1.0 	Backend library: LWJGL version 3.2.2 build 10 	Backend API: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation 	GL Caps: Using framebuffer using OpenGL 3.0 	Using VBOs: Yes 	Is Modded: Definitely; Client brand changed to 'forge' 	Type: Client (map_client.txt) 	Graphics mode: fancy 	Resource Packs: mod_resources, vanilla, programer_art 	Current Language: 한국어 (대한민국) 	CPU: 12x Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz 	OptiFine Version: OptiFine_1.16.4_HD_U_G5 	OptiFine Build: 20201106-171901 	Render Distance Chunks: 20 	Mipmaps: 4 	Anisotropic Filtering: 1 	Antialiasing: 0 	Multitexture: false 	Shaders: SEUS-Renewed-v1.0.1.zip 	OpenGlVersion: 4.6.0 NVIDIA 452.06 	OpenGlRenderer: GeForce GTX 1660/PCIe/SSE2 	OpenGlVendor: NVIDIA Corporation 	CpuCount: 12

**Comment by Daejangnamu** [comment] 2020-11-24 09:59
Sometimes crashes when the player is flying in the sky

**Comment by pau101** [comment] 2020-11-24 10:51
Thanks for reporting!

This appears to be a duplicate of #93. You can try a new testing version to resolve the problem. [Download](https://drive.google.com/file/d/1HJ244NV5y8gFgz2P1LrXKr5L0pztHKNf/view?usp=sharing)

**Closed by pau101** 2020-11-24 10:51 UTC
