### ISSUE TITLE
Lights don't render when being hanged on any fence

### ISSUE THREAD

**Issue by galaxyspectator** [pau101/Fairy-Lights#69] opened 2019-12-23 15:32 UTC
I use optifine but the mod worked correctly before. Latest version of 1.12.2. No resource pack.
![image](https://user-images.githubusercontent.com/50798725/71366228-7ffe4c80-25b2-11ea-988d-5bf738f7ba8b.png)

**Comment by pau101** [comment] 2019-12-24 00:23
Thanks for reporting!

I am unable to reproduce with just Fairy Lights and OptiFine, what other mods do you have installed?

**Comment by TheLunarArtemis** [comment] 2020-01-01 05:38
I'm having this exact same issue. the lights place when on blocks, but any fence type blocks (modded, vanilla, iron bars, etc) it renders as invisible.
I'm not sure what mods OP is using, but this is my mods list: https://imgur.com/a/jHtyPPX

**Comment by galaxyspectator** [comment] 2020-01-02 18:15
> Thanks for reporting!
> 
> I am unable to reproduce with just Fairy Lights and OptiFine, what other mods do you have installed?

my modpack is here ![image](https://user-images.githubusercontent.com/50798725/71683921-e6e6e700-2da4-11ea-8eb0-61c38bad4c30.png)

**Comment by pau101** [comment] 2020-01-02 21:08
When did this start happening? Did you update a specific mod?

**Comment by pau101** [comment] 2020-02-01 11:05
Fixed in [2.1.10](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/2857644)

**Closed by pau101** 2020-02-01 11:05 UTC
Labels: bug
