### ISSUE TITLE
Issue with Missing texture of Bunting and Letter Buntings.

### ISSUE THREAD

**Issue by Atenberus** [pau101/Fairy-Lights#97] opened 2020-11-22 23:34 UTC
Hello! I've noticed in the 1.16.3-1.16.4 versions of the mod the letter bunting and pennant bunting appear as the black and purple missing textures box. Even if it is the only mod installed.

**Comment by pau101** [comment] 2020-11-23 01:40
Thanks for reporting!

I am unable to reproduce this using latest forge, which have you tried? If the issue is experienced on latest could you provide me the logs at "logs/debug.log".

**Comment by EccentricBeing** [comment] 2020-11-23 03:28
I am also experiencing this. I have tried updating both the mod and forge, though I have a lot of mods installed so don't know if I could be as much help ^^'
Unsure if this is the correct thing? First time using github, sorry
[latest.log](https://github.com/pau101/Fairy-Lights/files/5580985/latest.log)

**Comment by pau101** [comment] 2020-11-23 03:54
@EccentricBeing can you try updating to [latest forge](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.16.4.html)? The log shows 35.0.18 which is quite old, other than that nothing stands out.

**Comment by EccentricBeing** [comment] 2020-11-23 04:14
Oh whoops don't know how I didn't get the latest forge haha. Did that and still getting the error boxes for some reason
[latest.log](https://github.com/pau101/Fairy-Lights/files/5581068/latest.log)

**Comment by pau101** [comment] 2020-11-23 04:36
Thank you, could you provide a screenshot of what you see?

**Comment by EccentricBeing** [comment] 2020-11-23 05:01
Sure thing
![2020-11-22_22 59 48](https://user-images.githubusercontent.com/74888332/99930414-8fcc6680-2d16-11eb-835f-65f76b94d7a1.png)

**Comment by pau101** [comment] 2020-11-23 05:20
Okay good, just confirming. Could you provide the "debug.log" specifically, it will provide more information than the "latest.log"

**Comment by EccentricBeing** [comment] 2020-11-23 05:27
Is this the right one? 
[debug.log](https://github.com/pau101/Fairy-Lights/files/5581200/debug.log)

**Comment by pau101** [comment] 2020-11-23 05:44
Yes thank you, could you test if this [build](https://drive.google.com/file/d/1D5y9SFzgcLTfE-e9dgaGZhkVbJL-glrs/view?usp=sharing) of the mod resolves the issue?

**Comment by EccentricBeing** [comment] 2020-11-24 01:22
Ah it did! Thank you!

**Comment by pau101** [comment] 2020-12-08 21:56
Now resolved in [4.0.3](https://www.curseforge.com/minecraft/mc-mods/fairy-lights/files/3134283).

**Closed by pau101** 2020-12-08 21:56 UTC
