### ISSUE TITLE
Fairy Lights on a String Crash

### ISSUE THREAD

**Issue by Darkosto** [pau101/Fairy-Lights#9] opened 2017-01-04 17:17 UTC
Heya,

Is this an issue you've seen yet?

https://forum.feed-the-beast.com/threads/fairy-lights-string-will-cause-client-to-crash-when-placed-in-world.211311/

Looks like a crash when placing certain fairy lights: http://paste.feed-the-beast.com/view/9c5e4ee9 

Mod Version: 2.0.3
Forge: 2185

Thank you for checking this out :) 
Darkosto

**Comment by pau101** [comment] 2017-01-04 18:45
Thanks for the report, This is a duplicate of #7 and is fixed in [2.0.4](https://minecraft.curseforge.com/projects/fairy-lights/files/2362193)

**Closed** 2017-01-09 00:46 UTC
Labels: duplicate
